import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Janeesh | Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
   
      </div>  
  )
}
